name: Docker

on: 
  workflow_dispatch:
    inputs:
      golang:
        description: GoLang Version
        required: true
      goreleaser:
        description: GoReleaser Version
        required: true

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: arekkas
          password: ${{ secrets.DOCKER_SECRET_AREKKAS }}

      - name: Build and push image
        run: |
          go_version="${{ github.event.inputs.golang }}"
          goreleaser_version="${{ github.event.inputs.goreleaser }}"
          docker buildx build \
            --build-arg GO_VERSION=${go_version} --build-arg GORELEASER_VERSION=${goreleaser_version} \
            -t oryd/xgoreleaser:${go_version}-${goreleaser_version} .
            --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \ --tag your-username/multiarch-example:buildx-latest .
          docker tag oryd/xgoreleaser:${go_version}-${goreleaser_version} oryd/xgoreleaser:latest
          docker push oryd/xgoreleaser:${go_version}-${goreleaser_version}
          docker push oryd/xgoreleaser:latest
